To set up and run the web server:
1. In terminal, navigate to the folder that contains 'WebServer.java' file
2. Execute the following command to compile the code: javac WebServer.java
3. Run the code by replacing -document_root value and -port value with values of your choice: java WebServer -document_root "C:\Users\ajite\OneDrive\Documents\COEN 317 - DS\Resources" -port 8000
4. In a web browser navigate to http://localhost:<your_portnumber_here> and make requests for files that are present in the root directory mentioned in the previous command.

(Refer to Server Log screenshot in readme if required)